# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainview.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 339)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 21, 71, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 60, 71, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(450, 101, 71, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.Origin_context_dir = QtWidgets.QLineEdit(self.centralwidget)
        self.Origin_context_dir.setEnabled(False)
        self.Origin_context_dir.setGeometry(QtCore.QRect(140, 20, 301, 21))
        self.Origin_context_dir.setObjectName("Origin_context_dir")
        self.Split_result_dir = QtWidgets.QLineEdit(self.centralwidget)
        self.Split_result_dir.setEnabled(False)
        self.Split_result_dir.setGeometry(QtCore.QRect(140, 60, 301, 21))
        self.Split_result_dir.setObjectName("Split_result_dir")
        self.TF_output_dir = QtWidgets.QLineEdit(self.centralwidget)
        self.TF_output_dir.setEnabled(False)
        self.TF_output_dir.setGeometry(QtCore.QRect(140, 100, 301, 21))
        self.TF_output_dir.setObjectName("TF_output_dir")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setEnabled(False)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 170, 501, 101))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(410, 280, 113, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "詞頻計算程式"))
        self.label.setText(_translate("MainWindow", "原始文本目錄"))
        self.label_2.setText(_translate("MainWindow", "斷詞結果輸出目錄"))
        self.pushButton.setText(_translate("MainWindow", "選取"))
        self.pushButton_2.setText(_translate("MainWindow", "選取"))
        self.label_3.setText(_translate("MainWindow", "詞頻結果輸出目錄"))
        self.pushButton_3.setText(_translate("MainWindow", "選取"))
        self.label_4.setText(_translate("MainWindow", "訊息提示"))
        self.pushButton_4.setText(_translate("MainWindow", "執行"))
